# Each new term in the Fibonacci Sq is generated by adding the previous two terms. By starting with 1,2
# By Considering the terms in the Fibonacci sq whose values do not exceed four million, find the sum of the even-values terms.


evenfibsum = 2
oddfibsum = 1
lastvalue = 2
secondlastvalue = 1
while lastvalue <= 4*10**6:
        secondlastvalue, lastvalue = lastvalue, lastvalue + secondlastvalue
        #bit wise operation to check the value is even
        if not lastvalue & 1:
                evenfibsum += lastvalue
        else:
                oddfibsum += lastvalue
                

print(evenfibsum)



#O(n) time complexity
#O(1) space 

